Repository Smart-Meal-Prep/smart-meal-planning, pull requests merged in 2023-12, with the labels that each got.

#34 SM-55-Front-end-auth
  front-end/src/App.js
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/Dashboard/DashboardFooter.js
  front-end/src/component/Dashboard/NavigationBar.js
  front-end/src/component/management/Inventory.js
  front-end/src/component/management/Recipes.js
  front-end/src/component/user/Login.js
  front-end/src/component/user/Profile.js
  front-end/src/component/user/Register.js
  front-end/src/config/UserInfo.js
Labels: enhancement

#35 SM-60-Login-UI
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/assets/overlay_2.png
  front-end/src/component/user/Login.js
  front-end/src/component/user/Login/Login.js
  front-end/src/component/user/Login/LoginNavbar.js
  front-end/src/styles/Login.css
  front-end/src/test/login.test.js
Labels: enhancement

#36 SM-61-Added-config-for-deploying
  front-end/package-lock.json
  front-end/package.json
Labels: enhancement

#37 SM-62-Change-build-location
  front-end/package.json
Labels: bug

#39 SM-64-Registration-UI
  front-end/src/App.js
  front-end/src/component/user/Register.js
  front-end/src/component/user/Register/Register.js
  front-end/src/styles/Registration.css
  front-end/src/test/registration.test.js
Labels: enhancement

#40 SM-65-Logout
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/Dashboard/NavigationBar.js
  front-end/src/config/fetch.js
Labels: enhancement

#41 SM-66-Env-set-up
  .gitignore
  server/config/config.js
  server/index.js
  server/models/index.js
  server/package-lock.json
  server/package.json
Labels: bug

#42 SM-66-Updated-inventory-path
  server/routes/Inventory.js
Labels: bug

#44 SM-66-Changed-cors-origin
  server/index.js
Labels: bug

#45 SM-66-Changed-port-number
  server/index.js
Labels: bug

#47 SM-66-Change-cors-origin
  server/index.js
Labels: bug

#48 SM-66-Reverted-cors-change
  server/index.js
Labels: bug

#50 SM-66-Cors-change
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/user/Login/Login.js
  server/index.js
Labels: bug

#51 SM-66-Cors-error-patch
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/user/Login/Login.js
  server/index.js
Labels: bug

#52 SM-66-Changed-origin
  server/index.js
Labels: bug

#53 SM-58-Inventory-UI
  front-end/src/App.js
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/DashboardFooter.js
  front-end/src/component/NavigationBar.js
  front-end/src/component/management/Inventory/Inventory.js
  front-end/src/component/management/Inventory/InventoryBody.js
  front-end/src/component/management/Recipes/Recipes.js
  front-end/src/component/management/Recipes/RecipesBody.js
  front-end/src/config/list.js
  front-end/src/styles/InventoryBody.css
  front-end/src/test/inventory.test.js
  server/controllers/Inventory.js
  server/routes/Inventory.js
Labels: enhancement

#54 SM-66-Added-samesite
  server/index.js
Labels: bug

#55 SM-66-Revert-change
  server/index.js
Labels: bug

#56 SM-67-Profile-setting-page
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/component/DashboardFooter.js
  front-end/src/component/user/Profile.js
  front-end/src/component/user/Profile/Profile.js
  front-end/src/styles/DashboardFooter.css
  front-end/src/styles/Profile.css
  front-end/src/test/profile.test.js
Labels: enhancement

#57 SM-68-Changed-user-info-retrieval
  front-end/src/component/Dashboard/Dashboard.js
  front-end/src/component/user/Login/Login.js
  server/controllers/Users.js
  server/test/login.test.js
Labels: enhancement

#58 SM-71-Readme
  README.md
Labels: documentation

#59 SM-73-Added-text-to-dashboard
  front-end/src/component/Dashboard/Dashboardbody.js
Labels: documentation

#61 SM-74: Added UI to favorites list in user profile
  front-end/src/App.js
  front-end/src/component/management/Recipes/Recipes.js
  front-end/src/component/management/Recipes/RecipesBody.js
  front-end/src/component/user/Profile/Profile.js
  front-end/src/styles/RecipesBody.css
Labels: enhancement
